services:
  healthcare_caduser:
    container_name: healthcare_cadusers
    image: cadusers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
        postgresqldb:
          condition: service_healthy
    environment:
      POSTGRES_HOST: postgresqldb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
  postgresqldb:
    container_name: postgresqldb
    image: postgres
    ports:
      - "5433:5432"
    user: postgres
    environment:
      POSTGRES_HOST: postgresqldb
      POSTGRES_DB: healthcare
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 2
    volumes:
      - /c/DockerVolumes/postgresql/:/var/lib/postgresql

